# Generated by Django 5.0.1 on 2024-06-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=122)),
                ('email', models.CharField(default='NULL', max_length=122)),
                ('subject', models.CharField(default='NULL', max_length=100)),
                ('message', models.CharField(default='NULL', max_length=1000)),
            ],
        ),
    ]
